# -*- coding: utf-8 -*-
"""BATCH6DAY4_ASSIGNMENT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gn07pvouOav_Qf0zi_IBTnc50vJ3J4N1
"""

#Question 1
ip_str=input("please enter your string : ")
find_str=input("For which word you want to search? : ")
index_i=ip_str.rfind(find_str)
print(index_i)

#Question2
str_i="PRITAM"
str_i.isupper()