# -*- coding: utf-8 -*-
"""BATCH6DAY5_ASSIGNMENT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ii3k0pxtNXXvifW3_JjixpxE8X16io2D
"""

list1=[45,1,34,2,6,9,5,34,90,96,64,4]
sorted_list=[]
no_of_element=len(list1)
while (len(sorted_list)<no_of_element):
  least_num=list1[0]
  for i in range(0,len(list1)):
    if(least_num<=list1[i]):
      pass
    else:
      least_num=list1[i]

  sorted_list.append(least_num)
  list1.remove(least_num)

print(sorted_list)